
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/contestgo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet.allow: true

# 热部署生效spring:
# 设置重启的目录,添加那个目录的文件需要restart
# 为mybatis设置，生产环境可删除
# 排除那个目录的文件不需要restart
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#      include:
#        mapper: /mapper-[\\w-\\.]+jar
#        pagehelper: /pagehelper-[\\w-\\.]+jar
#     exclude: static/**, public/**, WEB-INF/**

# Redis配置
# Redis数据库索引（默认为0）
# Redis服务器地址:
# Redis服务器连接端口
# Redis服务器连接密码（默认为空）
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
#    timeout: 0

  mail:
    host: smtp.qq.com
    username: 501315555@qq.com
    # 设置密码，该处的密码是QQ邮箱开启SMTP的授权码而非QQ密码
    # cvlveqbsyocibjaf
    password:  dsqtscyrwkgacafg
    # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8